return {
[1]={
	["type"]="constructor",
	["stateMutability"]="nonpayable",
	["inputs"]={
		[1]={
			["type"]="address",
			["internalType"]="contract IERC20",
			["name"]="_token",
			},
		[2]={
			["type"]="address",
			["internalType"]="address payable",
			["name"]="_dev",
			},
		[3]={
			["type"]="address",
			["internalType"]="address payable",
			["name"]="_invest",
			},
		},
	},
[2]={
	["anonymous"]=false,
	["type"]="event",
	["inputs"]={
		[1]={
			["indexed"]=false,
			["internalType"]="uint256",
			["name"]="",
			["type"]="uint256",
			},
		},
	["name"]="Claimed",
	},
[3]={
	["anonymous"]=false,
	["type"]="event",
	["inputs"]={
		[1]={
			["indexed"]=false,
			["internalType"]="uint256",
			["name"]="",
			["type"]="uint256",
			},
		[2]={
			["indexed"]=false,
			["internalType"]="uint256",
			["name"]="",
			["type"]="uint256",
			},
		},
	["name"]="Deposit",
	},
[4]={
	["anonymous"]=false,
	["type"]="event",
	["inputs"]={
		[1]={
			["indexed"]=false,
			["internalType"]="uint256",
			["name"]="",
			["type"]="uint256",
			},
		[2]={
			["indexed"]=false,
			["internalType"]="uint256",
			["name"]="",
			["type"]="uint256",
			},
		[3]={
			["indexed"]=false,
			["internalType"]="uint256",
			["name"]="",
			["type"]="uint256",
			},
		},
	["name"]="ICOEnded",
	},
[5]={
	["anonymous"]=false,
	["type"]="event",
	["inputs"]={
		[1]={
			["indexed"]=false,
			["internalType"]="address",
			["name"]="",
			["type"]="address",
			},
		[2]={
			["indexed"]=false,
			["internalType"]="address",
			["name"]="",
			["type"]="address",
			},
		},
	["name"]="NewAddressSet",
	},
[6]={
	["anonymous"]=false,
	["type"]="event",
	["inputs"]={
		[1]={
			["indexed"]=false,
			["internalType"]="uint256",
			["name"]="",
			["type"]="uint256",
			},
		[2]={
			["indexed"]=false,
			["internalType"]="uint256",
			["name"]="",
			["type"]="uint256",
			},
		},
	["name"]="NewICO",
	},
[7]={
	["stateMutability"]="nonpayable",
	["inputs"]={
		},
	["outputs"]={
		[1]={
			["type"]="bool",
			["internalType"]="bool",
			["name"]="",
			},
		},
	["name"]="Claim",
	["type"]="function",
	},
[8]={
	["stateMutability"]="nonpayable",
	["inputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="_phase",
			},
		},
	["outputs"]={
		[1]={
			["type"]="bool",
			["internalType"]="bool",
			["name"]="",
			},
		},
	["name"]="ClaimX",
	["type"]="function",
	},
[9]={
	["stateMutability"]="nonpayable",
	["inputs"]={
		[1]={
			["type"]="address",
			["internalType"]="address",
			["name"]="_new",
			},
		},
	["outputs"]={
		},
	["name"]="addOwner",
	["type"]="function",
	},
[10]={
	["stateMutability"]="view",
	["inputs"]={
		},
	["outputs"]={
		[1]={
			["type"]="address",
			["internalType"]="address",
			["name"]="",
			},
		},
	["name"]="controller",
	["type"]="function",
	},
[11]={
	["stateMutability"]="payable",
	["inputs"]={
		},
	["outputs"]={
		[1]={
			["type"]="bool",
			["internalType"]="bool",
			["name"]="",
			},
		},
	["name"]="depositX",
	["type"]="function",
	},
[12]={
	["stateMutability"]="view",
	["inputs"]={
		},
	["outputs"]={
		[1]={
			["type"]="address",
			["internalType"]="address payable",
			["name"]="",
			},
		},
	["name"]="development",
	["type"]="function",
	},
[13]={
	["stateMutability"]="nonpayable",
	["inputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="_allocToken",
			},
		},
	["outputs"]={
		[1]={
			["type"]="bool",
			["internalType"]="bool",
			["name"]="",
			},
		},
	["name"]="endICO",
	["type"]="function",
	},
[14]={
	["stateMutability"]="view",
	["inputs"]={
		},
	["outputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="",
			},
		},
	["name"]="getClaim",
	["type"]="function",
	},
[15]={
	["stateMutability"]="view",
	["inputs"]={
		[1]={
			["type"]="address",
			["internalType"]="address",
			["name"]="_target",
			},
		},
	["outputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="",
			},
		},
	["name"]="getClaimFor",
	["type"]="function",
	},
[16]={
	["stateMutability"]="view",
	["inputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="_phase",
			},
		},
	["outputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="",
			},
		},
	["name"]="getClaimX",
	["type"]="function",
	},
[17]={
	["stateMutability"]="view",
	["inputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="_phase",
			},
		[2]={
			["type"]="address",
			["internalType"]="address",
			["name"]="_target",
			},
		},
	["outputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="",
			},
		},
	["name"]="getClaimXFor",
	["type"]="function",
	},
[18]={
	["stateMutability"]="view",
	["inputs"]={
		},
	["outputs"]={
		[1]={
			["type"]="address",
			["internalType"]="address payable",
			["name"]="",
			},
		},
	["name"]="investment",
	["type"]="function",
	},
[19]={
	["stateMutability"]="view",
	["inputs"]={
		},
	["outputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="",
			},
		},
	["name"]="lastPhase",
	["type"]="function",
	},
[20]={
	["stateMutability"]="view",
	["inputs"]={
		},
	["outputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="",
			},
		},
	["name"]="minDeposit",
	["type"]="function",
	},
[21]={
	["stateMutability"]="view",
	["inputs"]={
		[1]={
			["type"]="address",
			["internalType"]="address",
			["name"]="",
			},
		},
	["outputs"]={
		[1]={
			["type"]="bool",
			["internalType"]="bool",
			["name"]="",
			},
		},
	["name"]="owners",
	["type"]="function",
	},
[22]={
	["stateMutability"]="view",
	["inputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="",
			},
		},
	["outputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="allocToken",
			},
		[2]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="totalDeposit",
			},
		[3]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="tokenPerWEI",
			},
		},
	["name"]="phaseInfo",
	["type"]="function",
	},
[23]={
	["stateMutability"]="view",
	["inputs"]={
		},
	["outputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="",
			},
		},
	["name"]="phaseNow",
	["type"]="function",
	},
[24]={
	["stateMutability"]="nonpayable",
	["inputs"]={
		[1]={
			["type"]="address",
			["internalType"]="address",
			["name"]="_tokenAddress",
			},
		[2]={
			["type"]="address",
			["internalType"]="address",
			["name"]="_to",
			},
		[3]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="_amount",
			},
		},
	["outputs"]={
		},
	["name"]="retrieveAnyERC20",
	["type"]="function",
	},
[25]={
	["stateMutability"]="nonpayable",
	["inputs"]={
		[1]={
			["type"]="address",
			["internalType"]="address",
			["name"]="_prev",
			},
		},
	["outputs"]={
		},
	["name"]="revokeOwner",
	["type"]="function",
	},
[26]={
	["stateMutability"]="view",
	["inputs"]={
		},
	["outputs"]={
		[1]={
			["type"]="address",
			["internalType"]="contract IERC20",
			["name"]="",
			},
		},
	["name"]="sector",
	["type"]="function",
	},
[27]={
	["stateMutability"]="nonpayable",
	["inputs"]={
		[1]={
			["type"]="address",
			["internalType"]="address payable",
			["name"]="_development",
			},
		[2]={
			["type"]="address",
			["internalType"]="address payable",
			["name"]="_investment",
			},
		},
	["outputs"]={
		[1]={
			["type"]="bool",
			["internalType"]="bool",
			["name"]="",
			},
		},
	["name"]="setAddressSet",
	["type"]="function",
	},
[28]={
	["stateMutability"]="nonpayable",
	["inputs"]={
		},
	["outputs"]={
		[1]={
			["type"]="bool",
			["internalType"]="bool",
			["name"]="",
			},
		},
	["name"]="setICO",
	["type"]="function",
	},
[29]={
	["stateMutability"]="view",
	["inputs"]={
		},
	["outputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="",
			},
		},
	["name"]="state",
	["type"]="function",
	},
[30]={
	["stateMutability"]="nonpayable",
	["inputs"]={
		[1]={
			["type"]="address",
			["internalType"]="address",
			["name"]="newController",
			},
		},
	["outputs"]={
		},
	["name"]="transferController",
	["type"]="function",
	},
[31]={
	["stateMutability"]="nonpayable",
	["inputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="_minDeposit",
			},
		},
	["outputs"]={
		},
	["name"]="updateMinDeposit",
	["type"]="function",
	},
[32]={
	["stateMutability"]="view",
	["inputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="",
			},
		[2]={
			["type"]="address",
			["internalType"]="address",
			["name"]="",
			},
		},
	["outputs"]={
		[1]={
			["type"]="uint256",
			["internalType"]="uint256",
			["name"]="amount",
			},
		},
	["name"]="userInfo",
	["type"]="function",
	},
[33]={
	["type"]="receive",
	["stateMutability"]="payable",
	},
}
